<a href="https://colab.research.google.com/github/ritikarpawar/Tensorflow/blob/main/tensorflowprac.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import tensorflow as tf

marks = tf.constant([
    [80, 75, 90],
    [70, 85, 88]
], dtype=tf.float32)

print("Student Marks:\n", marks.numpy())

total_marks_student1 = tf.reduce_sum(marks[0])
total_marks_student2 = tf.reduce_sum(marks[1])

print("\nTotal Marks of Student 1:", total_marks_student1.numpy())
print("Total Marks of Student 2:", total_marks_student2.numpy())

average_student1 = tf.reduce_mean(marks[0])
average_student2 = tf.reduce_mean(marks[1])

print("\nAverage Marks of Student 1:", average_student1.numpy())
print("Average Marks of Student 2:", average_student2.numpy())

highest_mark = tf.reduce_max(marks)
lowest_mark = tf.reduce_min(marks)

print("\nHighest Mark:", highest_mark.numpy())
print("Lowest Mark:", lowest_mark.numpy())

difference = marks[0] - marks[1]

print("\nSubject-wise Difference:")
print(difference.numpy())

weights = tf.constant([0.3, 0.3, 0.4], dtype=tf.float32)

weighted_scores = marks * weights

print("\nWeighted Scores:")
print(weighted_scores.numpy())

normalized_marks = marks / tf.reduce_max(marks)

print("\nNormalized Marks:")
print(normalized_marks.numpy())

squared_marks = tf.square(marks)

print("\nSquared Marks:")
print(squared_marks.numpy())

weights_matrix = tf.reshape(weights, (3, 1))

final_grades = tf.matmul(marks, weights_matrix)

print("\nFinal Grades:")
print(final_grades.numpy())

bonus_marks = tf.constant([[5], [5]], dtype=tf.float32)

final_result = final_grades + bonus_marks

print("\nFinal Result after Bonus:")
print(final_result.numpy())

Student Marks:
 [[80. 75. 90.]
 [70. 85. 88.]]

Total Marks of Student 1: 245.0
Total Marks of Student 2: 243.0

Average Marks of Student 1: 81.666664
Average Marks of Student 2: 81.0

Highest Mark: 90.0
Lowest Mark: 70.0

Subject-wise Difference:
[ 10. -10.   2.]

Weighted Scores:
[[24.       22.5      36.      ]
 [21.       25.500002 35.2     ]]

Normalized Marks:
[[0.8888889 0.8333333 1.       ]
 [0.7777778 0.9444444 0.9777778]]

Squared Marks:
[[6400. 5625. 8100.]
 [4900. 7225. 7744.]]

Final Grades:
[[82.5]
 [81.7]]

Final Result after Bonus:
[[87.5]
 [86.7]]
